### ISSUE TITLE
not work for network with residual structure?

### ISSUE THREAD

**Issue by zhuhong** [Lyken17/pytorch-memonger#1]
It looks like SublinearSequential redefined the foward pass of the network in momonger/memonger.py as follow:

 42     def normal_forward(self, input):
 43         for module in self._modules.values():
 44             input = module(input)
 45         return input

So, this redefine maybe not work for residual network like resnet50.

Besides, when there are some flatten ops in the original foward function, like x.view(x.size(0),-1), they will be skiped by SublinearSequential forward function  as I think and it will make some mismatch for the network;

**Comment by Lyken17** [comment]
note, the original purpose of `SublinearSequential` is to replace `nn.Sequential`. If you are using other blocks, you need to wrap it into sequential style.
