### ISSUE TITLE
backward pass

### ISSUE THREAD

**Issue by cnzhanj** [Lyken17/pytorch-memonger#3]
Hi @Lyken17 

It looks like that the train data go through forward pass in checkpoint.py(function forward), But, when I use loss.backward, it looks like did not call backward function in checkpoint.py, instead it calls the initial backward function in torch.autograd.function.py? and the backward is not working because I print the model parameter values after each iteration. what's more, the speed in Subliner is faster than Sequential? 

That is, have you reconstructthe backward function?

**Comment by Lyken17** [comment]
> when I use loss.backward, it looks like did not call backward function in checkpoint.py

The backward function is modified. You can check the codes around https://github.com/Lyken17/pytorch-memonger/blob/master/momonger/checkpoint.py#L62 If it is not working, please attach a minimal code for reproducing. 

> and the backward is not working because I print the model parameter values after each iteration

Not sure what your case is.

> the speed in Subliner is faster than Sequential

The sublinear should be slower than sequential.

**Comment by cnzhanj** [comment]
`def train(train_loader, model, criterion, optimizer, epoch, args):
    batch_time = AverageMeter('Time', ':6.3f')
    data_time = AverageMeter('Data', ':6.3f')
    losses = AverageMeter('Loss', ':.4e')
    top1 = AverageMeter('Acc@1', ':6.2f')
    top5 = AverageMeter('Acc@5', ':6.2f')
    progress = ProgressMeter(
        len(train_loader),
        [batch_time, data_time, losses, top1, top5],
        prefix="Epoch: [{}]".format(epoch))

    # switch to train mode
    model.train()

    end = time.time()
    for i, (images, target) in enumerate(train_loader):
        # measure data loading time
        data_time.update(time.time() - end)

        if args.gpu is not None:
            images = images.cuda(args.gpu, non_blocking=True)
        target = target.cuda(args.gpu, non_blocking=True)

        # compute output
        output = model(images)
        loss = criterion(output, target)
        
        # measure accuracy and record loss
        acc1, acc5 = accuracy(output, target, topk=(1, 5))
        losses.update(loss.item(), images.size(0))
        top1.update(acc1[0], images.size(0))
        top5.update(acc5[0], images.size(0))

        # compute gradient and do SGD step
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # measure elapsed time
        batch_time.update(time.time() - end)
        end = time.time()

        if i % args.print_freq == 0:
            progress.display(i)
`



I just use the pytorch example code for imagenet, and the model is Sublinear，

**Comment by cnzhanj** [comment]
And, 
`output = model(images)`
will call forward function in checkpoint.py, But
`loss.backward()`
will NOT call backward function in checkpoint.py

and, this is the resullt when I train a model:
`Epoch: [0][    0/20019] Time  5.393 ( 5.393) Data  4.341 ( 4.341) cached_memory  0.12 ( 0.12) max_cached_memory  0.12 ( 0.12) Loss 7.0115e+00 (7.0115e+00) Acc@1   0.00 (  0.00) Acc@5   1.56 (  1.56)
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
backward: 0.001424551010131836
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
call forward function in checkpoint
Epoch: [0][   10/20019] Time  0.084 ( 1.012) Data  0.000 ( 0.840) cached_memory  1.88 ( 1.59) max_cached_memory  3.19 ( 2.91) Loss 2.0177e+01 (1.6802e+01) Acc@1   0.00 (  0.00) Acc@5   3.12 (  0.71)`

**Comment by cnzhanj** [comment]
Thank you!
I use the example resnet in momonger, and modify the code (add loss.backward) and it did call backward function, but as for other model it didn't, what's the error?

and I found, as for other model, it should change the output size? Is this cause the error?
@Lyken17

**Comment by cnzhanj** [comment]
it is necessary to add the torch.flatten for align the tensors? Because the error occurs in alexnet:
`output = input.matmul(weight.t())`
`RuntimeError: size mismatch, m1: [1536 x 6], m2: [9216 x 4096] at`

**Comment by Lyken17** [comment]
Sublinear only supports nn.Sequential. Other operations are not considered at the moment.

**Comment by cnzhanj** [comment]
Thank you! I will modify the vgg code and add nn.Sequential to the model as to suit for Sublinear , But it seems not work?

**Comment by Lyken17** [comment]
When something does work, show me the code (minimal case for reproducement) instead of simply telling me it. I am not a magician and cannot read your mind.
